2021-01-12 16:07:50,631 ERROR [D:\10_work\10_udemy\07_Django\02_source\03_source\ClassBasedView\class_based_view\store\views.py:48] この名前は利用できません
NoneType: None
